# 一致性构建镜像 buildah bud --no-cache -f dockerfiles -t 容器名

FROM aspnmy/debian-ssh:s6-overlay-v12.7-devworker-base


WORKDIR /sh
RUN mkdir -p /sh/cfworktools && apt update && apt install -y jq
COPY /app/cfworktools/install_cftest.sh /sh/cfworktools/install_cftest.sh

RUN  chmod +x /sh/cfworktools/install_cftest.sh  && rm -rf /var/lib/apt/lists/* && rm -rf /tmp/*


# 暴露622端口
EXPOSE 622



# 设置s6-overla:v${S6_OVERLAY_VERSION}全局的ENTRYPOINT
ENTRYPOINT ["/init"]

CMD [ "./start.sh" ]
