# 一致性构建镜像 buildah bud --no-cache -f dockerfiles -t 容器名
# 从官方镜像重新构建降低镜像大小
FROM debian:latest

ARG S6_OVERLAY_VERSION=3.2.0.2
# 更改主服务名称 只需在此配置变量名即可 其他服务无需理会
ARG S6_OVERLAY_SERVIES=sshd
# 主服务项目PATH
ARG S6_SERVIES_PATH=/etc/s6-overlay/s6-rc.d/${S6_OVERLAY_SERVIES}
# 主服务项目RUNTIMES_PATH_01
ARG S6_SERVIES_RUNTIMES_PATH_01=/var/run/${S6_OVERLAY_SERVIES}
# 主服务项目RUNTIMES_PATH_02
ARG S6_SERVIES_RUNTIMES_PATH_02=/root/run/${S6_OVERLAY_SERVIES}


# 下面是固定的业务常量不需要修改
# S6_OVERLAY_USER_PATH_01
ARG S6_OVERLAY_USER_PATH_01=/etc/s6-overlay/s6-rc.d/user/contents.d

# S6_OVERLAY_USER_PATH_02
ARG S6_OVERLAY_USER_PATH_02=/etc/s6-overlay/s6-rc.d/user2/contents.d

# S6_OVERLAY_UPDATE_URL
ARG S6_OVERLAY_UPDATE_URL=https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}

#### --构建主服务${S6_OVERLAY_SERVIES}语句-开始
# 更新软件包列表
RUN apt-get update && apt-get install -y sudo openssh-server xz-utils  dos2unix




# 生成主服务${S6_OVERLAY_SERVIES}运行目录配置权限
RUN  mkdir ${S6_SERVIES_RUNTIMES_PATH_01} && chmod 700 ${S6_SERVIES_RUNTIMES_PATH_01} && chown root:root ${S6_SERVIES_RUNTIMES_PATH_01}



#### --构建主服务${S6_OVERLAY_SERVIES}语句-结束

#### --构建超级进程服务${S6_OVERLAY_SERVIES}语句-开始-不清楚不要改
# ----安装S6_OVERLAY-github下载最新版s6-overlay 不需要更改
ADD ${S6_OVERLAY_UPDATE_URL}/s6-overlay-noarch.tar.xz /tmp
ADD ${S6_OVERLAY_UPDATE_URL}/s6-overlay-x86_64.tar.xz /tmp
RUN tar -C / -Jxpf /tmp/s6-overlay-noarch.tar.xz && tar -C / -Jxpf /tmp/s6-overlay-x86_64.tar.xz


# 使用s6新版配置格式配置 创建${S6_OVERLAY_SERVIES}服务脚本并配置权限

# 新增${S6_OVERLAY_SERVIES}工作路径
RUN mkdir -p ${S6_SERVIES_PATH}  && mkdir -p ${S6_SERVIES_PATH}/dependencies.d && touch ${S6_OVERLAY_USER_PATH_01}/${S6_OVERLAY_SERVIES} && touch ${S6_SERVIES_PATH}/dependencies.d/base

# 复制${S6_OVERLAY_SERVIES}工作脚本到主路径
COPY /app/${S6_OVERLAY_SERVIES}.type ${S6_SERVIES_PATH}/type
COPY /app/${S6_OVERLAY_SERVIES}.run ${S6_SERVIES_PATH}/run
COPY /app/${S6_OVERLAY_SERVIES}.finish ${S6_SERVIES_PATH}/finish

# 配置脚本正确字符串
# debug S6-Supervise (child): S6 Fatal: Unable to spawn ./run: No such file or directory
RUN for file in ${S6_SERVIES_PATH}/*/*; do \
dos2unix $file; \
chmod a+xwr $file; \
done

# 配置主服务${S6_OVERLAY_SERVIES}脚本权限
# RUN chmod +x ${S6_SERVIES_PATH}/type && chmod +x ${S6_SERVIES_PATH}/run && chmod +x ${S6_SERVIES_PATH}/finish
#### --构建超级进程服务${S6_OVERLAY_SERVIES}语句-结束


# 暴露622端口
EXPOSE 622


# 清理缓存减小容器体积
RUN sudo apt remove -y xz-utils dos2unix && sudo apt autoremove -y && sudo rm -rf /var/lib/apt/lists/* && sudo rm -rf /tmp/*

# 设置s6-overla:v${S6_OVERLAY_VERSION}全局的ENTRYPOINT
ENTRYPOINT ["${S6_SERVIES_PATH}/run/${S6_OVERLAY_SERVIES}.run"]
