# 一致性构建镜像 buildah bud --no-cache -f dockerfiles -t 容器名

FROM aspnmy/debian-ssh:s6-overlay-v3.2.0.2-v12.7-base  AS dev-base

# 通过重建基础镜像 来降低镜像体积

ARG S6_OVERLAY_VERSION=3.2.0.2
# 更改主服务名称 只需在此配置变量名即可 其他服务无需理会
ARG S6_OVERLAY_SERVIES=sshd
# 主服务项目PATH
ARG S6_SERVIES_PATH=/etc/s6-overlay/s6-rc.d/${S6_OVERLAY_SERVIES}
# 主服务项目RUNTIMES_PATH_01
ARG S6_SERVIES_RUNTIMES_PATH_01=/var/run/${S6_OVERLAY_SERVIES}
# 主服务项目RUNTIMES_PATH_02
ARG S6_SERVIES_RUNTIMES_PATH_02=/root/run/${S6_OVERLAY_SERVIES}


# 下面是固定的业务常量不需要修改
# S6_OVERLAY_USER_PATH_01
ARG S6_OVERLAY_USER_PATH_01=/etc/s6-overlay/s6-rc.d/user/contents.d

# S6_OVERLAY_USER_PATH_02
ARG S6_OVERLAY_USER_PATH_02=/etc/s6-overlay/s6-rc.d/user2/contents.d

# S6_OVERLAY_UPDATE_URL
ARG S6_OVERLAY_UPDATE_URL=https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}

RUN mkdir -p /sh && mkdir -p /sh/cfworktools && apt update && apt install -y jq wget curl git 
#COPY /app/cfworktools/* /sh/cfworktools/
#COPY /app/start.sh  /sh/start.sh
#RUN  chmod +x /sh/start.sh  && 
RUN sudo apt autoremove -y && sudo rm -rf /var/lib/apt/lists/* && sudo rm -rf /tmp/*


# 暴露622端口
EXPOSE 622



# 设置s6-overla:v${S6_OVERLAY_VERSION}全局的ENTRYPOINT
ENTRYPOINT ["${S6_SERVIES_PATH}/run/${S6_OVERLAY_SERVIES}.run"]

#CMD [ "./start.sh" ]
