FROM docker.io/library/debian:latest
# 安装SSH服务
RUN apt-get update && apt-get install -y xz-utils
# 安装 s6-overlay服务
ADD tmp/v3.2.0.0/s6-overlay-noarch.tar.xz /tmp
RUN tar -C / -Jxpf ./tmp/s6-overlay-noarch.tar.xz
ADD tmp/v3.2.0.0/s6-overlay-x86_64.tar.xz /tmp
RUN tar -C / -Jxpf ./tmp/s6-overlay-x86_64.tar.xz
ENTRYPOINT ["/init"]

