# 一致性构建镜像 buildah bud --no-cache -f dockerfiles -t 容器名
FROM aspnmy/debian-ssh:s6-overlay-v12.7-devwork

# #替换为阿里源
RUN mv /etc/apt/sources.list /etc/apt/sources.list.backup
COPY /app/sources.list /etc/apt/sources.list
# 合并语句减小镜像体积
RUN   rm -rf /var/lib/apt/lists/* && rm -rf /tmp/*

WORKDIR /sh
# 暴露622端口
EXPOSE 622

# 设置s6-overla:v${S6_OVERLAY_VERSION}全局的ENTRYPOINT
ENTRYPOINT ["/init"]

CMD [ "./start.sh" ]
