# 一致性构建镜像 buildah bud --no-cache -f dockerfiles -t 容器名
# 定义基础镜像标签构建参数，默认值用于本地测试
#ARG BASE_IMAGE_TAG=aspnmy/debian-ssh:stable_s6-overlay_v3210_stable-20250908-slim

# 使用传入的基础镜像标签
FROM aspnmy/debian-ssh:stable_2025092313-workbase-s6-overlay_v3210_stable-20250908-slim

# # 复制root-sshkey管理工具
# /aspnmy/bin/setRootKey_Cli.sh 已经存在
# 使用git安装BestHostsMonitor
# 合并语句减小镜像体积
RUN bash /aspnmy/bin/gitBestHostsMonitor.sh \
    && echo "bash +x /aspnmy/bin/BestHostsMonitor/bin/server/runtasks.sh" >> "/init" \    
    && rm -rf /var/lib/apt/lists/* && rm -rf /tmp/* 

WORKDIR /aspnmy/bin
# 暴露622端口
EXPOSE 622

ENTRYPOINT ["/init"]
