# 一致性构建镜像 buildah bud --no-cache -f dockerfiles -t 容器名

FROM aspnmy/debian:base-v12.7

ARG S6_OVERLAY_VERSION=3.2.0.0
# 更改主服务名称 只需在此配置变量名即可 其他服务无需理会

# 下面是固定的业务常量不需要修改
# S6_OVERLAY_UPDATE_URL
ARG S6_OVERLAY_UPDATE_URL=https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}

#### --构建主服务${S6_OVERLAY_SERVIES}语句-开始
# 更新软件包列表
RUN apt-get update && apt-get install -y xz-utils openssh-server dos2unix

# 复制自定义的sshd_config文件
COPY /app/sshd_config /etc/ssh/sshd_config
# 复制SSH公钥(可选-如果使用密钥登录)
# COPY authorized_keys /root/.ssh/authorized_keys
# RUN chmod 600 /root/.ssh/authorized_keys


# 设置初始root密码
RUN echo 'root:root@#1314' | chpasswd

#### --构建主服务${S6_OVERLAY_SERVIES}语句-结束

#### --构建超级进程服务${S6_OVERLAY_SERVIES}语句-开始-不清楚不要改
# ----安装S6_OVERLAY-github下载最新版s6-overlay 不需要更改
ADD ${S6_OVERLAY_UPDATE_URL}/s6-overlay-noarch.tar.xz /tmp
ADD ${S6_OVERLAY_UPDATE_URL}/s6-overlay-x86_64.tar.xz /tmp
RUN tar -C / -Jxpf /tmp/s6-overlay-noarch.tar.xz && tar -C / -Jxpf /tmp/s6-overlay-x86_64.tar.xz


# 使用s6新版配置格式配置 创建${S6_OVERLAY_SERVIES}服务脚本并配置权限

# 旧版配置方式



# 暴露622端口
EXPOSE 622


# 清理缓存减小容器体积
RUN apt-get remove -y xz-utils dos2unix && rm -rf /var/lib/apt/lists/* && rm -rf /tmp/*

# 设置s6-overla:v${S6_OVERLAY_VERSION}全局的ENTRYPOINT
ENTRYPOINT ["/init"]

CMD [ "/usr/sbin/sshd","-D" ]