# 一致性构建镜像 buildah bud --no-cache -f dockerfiles -t 容器名

FROM aspnmy/debian-ssh:s6-overlay-v12.7-devworker-base



# # 复制root-sshkey管理工具
ADD /app/roottools/* /etc/ssh/
COPY start.sh /sh/start.sh
# 合并语句减小镜像体积
RUN  chmod +x /sh/start.sh && rm -rf /var/lib/apt/lists/* && rm -rf /tmp/*

WORKDIR /sh
# 暴露622端口
EXPOSE 622

ENTRYPOINT ["/init"]

CMD [ "./start.sh" ]
