# 一致性构建镜像 buildah bud --no-cache -f dockerfiles -t 容器名
FROM aspnmy/debian-ssh:stable_s6-overlay_v3210_stable-20250908-slim



# # 复制root-sshkey管理工具
# /aspnmy/bin/setRootKey_Cli.sh 已经存在
# 使用git安装BestHostsMonitor
# 合并语句减小镜像体积
RUN  apt-get -y git && bash /aspnmy/bin/gitBestHostsMonitor.sh 

RUN rm -rf /var/lib/apt/lists/* && rm -rf /tmp/*

WORKDIR /sh
# 暴露622端口
EXPOSE 622

ENTRYPOINT ["/init"]

CMD [ "./start.sh" ]
