# 一致性构建镜像 buildah bud --no-cache -f dockerfile-ssh-s6-overlay-cmd-update -t aspnmy/debian-ssh:s6-overlay-v12.7-rc1

FROM aspnmy/debian-ssh:s6-overlay-v12.7


# 更新软件包列表
RUN apt-get update && apt-get install -y wget curl sudo vim git wget && mkdir /sh
# 复制自定义的sshd_config文件
COPY /app/sshd_config /etc/ssh/sshd_config
# 复制SSH公钥(可选-如果使用密钥登录)
COPY authorized_keys /root/.ssh/authorized_keys
RUN chmod 600 /root/.ssh/authorized_keys
COPY start.sh /sh/start.sh
RUN chmod +x /sh/start.sh && rm -rf /var/lib/apt/lists/* && rm -rf /tmp/*
WORKDIR /sh
# 暴露622端口
EXPOSE 622



# 设置s6-overla:v${S6_OVERLAY_VERSION}全局的ENTRYPOINT
ENTRYPOINT ["/init"]

CMD [ "./start.sh" ]